version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
      POSTGRES_DB: ${NAME_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
